# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/miniai',
                'doc_host': 'https://ahadjawaid.github.io',
                'git_url': 'https://github.com/ahadjawaid/miniai',
                'lib_path': 'miniai'},
  'syms': { 'miniai.core': {'miniai.core.foo': ('core.html#foo', 'miniai/core.py')},
            'miniai.training': { 'miniai.training.Dataset': ('01-minibatch-training.html#dataset', 'miniai/training.py'),
                                 'miniai.training.Dataset.__getitem__': ( '01-minibatch-training.html#dataset.__getitem__',
                                                                          'miniai/training.py'),
                                 'miniai.training.Dataset.__init__': ('01-minibatch-training.html#dataset.__init__', 'miniai/training.py'),
                                 'miniai.training.Dataset.__len__': ('01-minibatch-training.html#dataset.__len__', 'miniai/training.py'),
                                 'miniai.training.accuracy': ('01-minibatch-training.html#accuracy', 'miniai/training.py'),
                                 'miniai.training.fit': ('01-minibatch-training.html#fit', 'miniai/training.py'),
                                 'miniai.training.get_dls': ('01-minibatch-training.html#get_dls', 'miniai/training.py'),
                                 'miniai.training.report': ('01-minibatch-training.html#report', 'miniai/training.py')}}}
